version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5000"  # Бэкенд доступен на порту 5000
    volumes:
      - ./backend:/app  # Монтируем локальную папку backend в контейнер
    environment:
      FLASK_ENV: development  # Включаем режим разработки (hot-reload для Flask)

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Фронтенд доступен на порту 3000
    volumes:
      - ./frontend:/app  # Монтируем локальную папку frontend в контейнер
      - /app/node_modules  # Исключаем node_modules
    command: npm start  # Запуск React-приложения с hot-reload