version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"