version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5000"  # Хост:Контейнер
    volumes:
      - ./backend:/app  # Синхронизация исходного кода
      - ./backend/instance:/app/instance  # Для сохранения данных SQLite
    environment:
      - FLASK_ENV=development  # Устанавливаем режим разработки
    command: python app.py  # Команда для запуска приложения

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Хост:Контейнер
    volumes:
      - ./frontend:/app  # Синхронизация исходного кода
      - /app/node_modules  # Исключаем node_modules из хоста
    environment:
      - NODE_ENV=development  # Устанавливаем режим разработки
    command: npm start  # Команда для запуска React